name: Deploy
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - name: GPG import
        run: cat <(echo -e "${{ secrets.OSSRH_GPG_KEY }}") | gpg --batch --import
      - name: GPG verify
        run: gpg --list-secret-keys --keyid-format LONG
      - name: GitHub checkout
        uses: actions/checkout@v2
      - name: GitHub setup-java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Maven clean
        run: mvn --batch-mode clean
      - name: Maven package
        run: mvn --batch-mode package
      - name: Maven deploy
        run: mvn --batch-mode --no-transfer-progress -Dgpg.passphrase=${{ secrets.OSSRH_GPG_PASSPHRASE }} deploy
        env:
          MAVEN_OPTS: --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.text=ALL-UNNAMED --add-opens=java.desktop/java.awt.font=ALL-UNNAMED
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
